name: Tests

on:
  push:
    branches:
      - master
      - '*.x'
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-22.04

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    strategy:
      fail-fast: false
      matrix:
        php: [ 8.1, 8.2 ]
        laravel: [ 9, 10 ]

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    env:
      extensions: curl, dom, gd, json, libxml, mbstring, zip
      key: php_${{ matrix.php }}_test_cache_v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup cache environment
        id: ext_cache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v3
        with:
          path: ${{ steps.ext_cache.outputs.dir }}
          key: ${{ steps.ext_cache.outputs.key }}
          restore-keys: ${{ steps.ext_cache.outputs.key }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, dom, gd, json, libxml, mbstring, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ env.key }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ env.key }}-${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer require "illuminate/contracts=^${{ matrix.laravel }}" --dev --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        if: ${{ matrix.laravel }} == 9
        run: ./vendor/bin/pest --coverage -vvv

      - name: Execute tests
        if: ${{ matrix.laravel }} != 9
        run: ./vendor/bin/pest --no-progress --coverage --profile -vvv
